name: infix
description: A lightweight Dart library that elegantly solves the code nesting problem using infix operators.
version: 2.0.0
repository: https://github.com/dzylikecode/infix

environment:
  sdk: "^3.5.0"

resolution: workspace

dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
